name: Benchmark on Emulator

on:
  workflow_dispatch:

jobs:
  benchmark-android:
    uses: Frozen-Bytes/actions/.github/workflows/android-macrobenchmark-gradle.yml@main
    with:
      api-level: 31
      target: google_apis
      arch: x86_64
      force-avd-creation: true
      emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -memory 4096
      disable-animations: true
      gradle-cache-readonly: false
      instrument-args: "-e class com.google.samples.apps.nowinandroid.startup.StartupBenchmark#startupPrecompiledWithBaselineProfile"
